version: "3.8"

services:
  webapp_sveltekit:
    container_name: webapp_sveltekit
    restart: unless-stopped
    depends_on: 
      - backend_node_api
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
#      - 24678:24678

  backend_node_api:
    container_name: backend_node_api
    restart: unless-stopped
    depends_on: 
      - backend_postgres
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 3000:3000

  backend_postgres:
    image: postgres:16.1-alpine3.19
    container_name: backend_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: mike
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  db_adminer:
    image: adminer
    restart: always
    depends_on: 
      - backend_postgres
    ports:
      - 8080:8080

volumes:
  pg_data:
    